changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: "Breaking Changes :warning:"
      labels:
        - breaking
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🛠
      labels:
        - bug
    - title: Documentations 📓
      labels:
        - documentation
    - title: Other Changes 📦
      labels:
        - "*"
